export * from './location.icon/location.icon'
export * from './phone.icon/phone.icon'
export * from './star-fill.icon/star-fill.icon'
export * from './star-emp.icon/star-emp.icon'
export * from './user.icon'
export * from './lock.icon'
export * from './note.icon'
export * from './bars.icon/bars.icon'
export * from './learn.icon/learn.icon'
export * from './user-fill.icon/user-fill.icon'
export * from './eye-sleep.icon'
export * from './eye-open.icon'

